-- MySQL Script generated by MySQL Workbench
-- 02/22/16 23:14:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MADES
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MADES` ;

-- -----------------------------------------------------
-- Schema MADES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MADES` DEFAULT CHARACTER SET utf8 ;
USE `MADES` ;

-- -----------------------------------------------------
-- Table `MADES`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MADES`.`treatment` ;

CREATE TABLE IF NOT EXISTS `MADES`.`treatment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treat1` VARCHAR(150) NULL,
  `treat2` VARCHAR(150) NULL,
  `treat3` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MADES`.`disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MADES`.`disease` ;

CREATE TABLE IF NOT EXISTS `MADES`.`disease` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MADES`.`symptom1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MADES`.`symptom1` ;

CREATE TABLE IF NOT EXISTS `MADES`.`symptom1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  `bodypart` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MADES`.`symptom2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MADES`.`symptom2` ;

CREATE TABLE IF NOT EXISTS `MADES`.`symptom2` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MADES`.`willhave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MADES`.`willhave` ;

CREATE TABLE IF NOT EXISTS `MADES`.`willhave` (
  `diseaseid` INT NOT NULL,
  `symptom1id` INT NULL,
  `symptom2id` INT NULL,
  `prob_num` INT NULL,
  `prob_den` INT NULL,
  PRIMARY KEY (`diseaseid`),
  INDEX `id_idx` (`symptom1id` ASC),
  INDEX `key3_idx` (`symptom2id` ASC),
  CONSTRAINT `key1`
    FOREIGN KEY (`diseaseid`)
    REFERENCES `MADES`.`disease` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `key2`
    FOREIGN KEY (`symptom1id`)
    REFERENCES `MADES`.`symptom1` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `key3`
    FOREIGN KEY (`symptom2id`)
    REFERENCES `MADES`.`symptom2` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MADES`.`has`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MADES`.`has` ;

CREATE TABLE IF NOT EXISTS `MADES`.`has` (
  `treatmentid` INT NOT NULL,
  `diseaseid` INT NULL,
  PRIMARY KEY (`treatmentid`),
  INDEX `key1_idx` (`diseaseid` ASC),
  CONSTRAINT `key1`
    FOREIGN KEY (`diseaseid`)
    REFERENCES `MADES`.`disease` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `key2`
    FOREIGN KEY (`treatmentid`)
    REFERENCES `MADES`.`treatment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
